// frontend/src/components/game/GameTable.tsx
import { useState, type MouseEvent, type ReactNode } from 'react'
import { Moon, Sun } from 'lucide-react'
import { cn } from '../../lib/utils'
import { useGameStore } from '../../store/useGameStore'
import { PlayerSeat, type SelectionMode } from './PlayerSeat'
import type { Player, GamePhase } from '../../types'
import { isWolfRole } from '../../types'

interface GameTableProps {
  selectionMode?: SelectionMode
  selectedTargetId?: number | null
  currentSpeakerId?: number | null
  onSelectPlayer?: (playerId: number) => void
  onHoverPlayer?: (playerId: number | null) => void
  onRightClickPlayer?: (playerId: number, e: MouseEvent) => void
  children?: ReactNode
}

const PLAYER_COUNT = 12
const ANGLE_PER_PLAYER = 360 / PLAYER_COUNT

export function GameTable({
  selectionMode = 'none',
  selectedTargetId = null,
  currentSpeakerId = null,
  onSelectPlayer,
  onHoverPlayer,
  onRightClickPlayer,
  children
}: GameTableProps) {
  const [hoveredPlayerId, setHoveredPlayerId] = useState<number | null>(null)
  
  // Connect to global store
  const players = useGameStore(state => state.gameState?.players || [])
  const myPlayer = useGameStore(state => state.gameState?.players.find(p => p.is_human))
  const currentPhase = useGameStore(state => state.gameState?.phase || '')
  const isGameOver = useGameStore(state => state.gameState?.phase === 'GAME_END')

  const isNight = (() => {
    const nightPhases: GamePhase[] = [
      'NIGHT_START', 'NIGHT_WOLF_DISCUSS', 'NIGHT_WOLF_VOTE',
      'NIGHT_SEER', 'NIGHT_WITCH', 'NIGHT_GUARD', 'NIGHT_RESOLVE'
    ]
    return nightPhases.includes(currentPhase as GamePhase)
  })()

  const selectionModeStyle = (() => {
    const styles: Record<SelectionMode, { icon: string; text: string; glowClass: string; textClass: string }> = {
      none: { icon: '', text: '', glowClass: '', textClass: '' },
      vote: { icon: '🗳️', text: '选择要投票的玩家', glowClass: 'ring-2 ring-blue-500/50 shadow-[0_0_15px_rgba(59,130,246,0.5)]', textClass: 'text-blue-400 font-bold' },
      kill: { icon: '🐺', text: '选择今晚要击杀的目标', glowClass: 'ring-2 ring-rose-500/50 shadow-[0_0_15px_rgba(244,63,94,0.5)]', textClass: 'text-rose-400 font-bold' },
      check: { icon: '🔮', text: '选择要查验的玩家', glowClass: 'ring-2 ring-fuchsia-500/50 shadow-[0_0_15px_rgba(217,70,239,0.5)]', textClass: 'text-fuchsia-400 font-bold' },
      protect: { icon: '🛡️', text: '选择要守护的玩家', glowClass: 'ring-2 ring-cyan-500/50 shadow-[0_0_15px_rgba(6,182,212,0.5)]', textClass: 'text-cyan-400 font-bold' },
      poison: { icon: '☠️', text: '选择要毒杀的玩家', glowClass: 'ring-2 ring-rose-600/50 shadow-[0_0_15px_rgba(225,29,72,0.5)]', textClass: 'text-rose-500 font-bold' },
      save: { icon: '💚', text: '选择要救的玩家', glowClass: 'ring-2 ring-emerald-500/50 shadow-[0_0_15px_rgba(16,185,129,0.5)]', textClass: 'text-emerald-400 font-bold' },
      shoot: { icon: '🔫', text: '选择要开枪带走的玩家', glowClass: 'ring-2 ring-orange-500/50 shadow-[0_0_15px_rgba(249,115,22,0.5)]', textClass: 'text-orange-400 font-bold' }
    }
    return styles[selectionMode] || styles['none']
  })()

  function getPlayerPositionStyle(playerId: number) {
    const angleDegrees = (playerId - 1) * ANGLE_PER_PLAYER - 90
    const angleRadians = angleDegrees * (Math.PI / 180)
    const radius = 42
    const x = 50 + radius * Math.cos(angleRadians)
    const y = 50 + radius * Math.sin(angleRadians)
    return { left: `${x}%`, top: `${y}%` }
  }

  function shouldShowRole(player: Player): boolean {
    if (player.is_human) return true
    if (isGameOver) return true
    if (myPlayer && isWolfRole(myPlayer.role) && isWolfRole(player.role)) return true
    return false
  }

  function canSelectPlayer(player: Player): boolean {
    if (selectionMode === 'none') return false
    if (!player.is_alive) return false
    if (!myPlayer) return false

    switch (selectionMode) {
      case 'vote': return player.id !== myPlayer.id
      case 'kill': return true
      case 'check': return player.id !== myPlayer.id
      case 'protect': return true
      case 'poison': return player.id !== myPlayer.id
      case 'save': return true
      case 'shoot': return player.id !== myPlayer.id
      default: return false
    }
  }

  return (
    <div className={cn("game-table", isNight ? "night-mode" : "day-mode")}>
      {/* 放射状布局容器 */}
      <div className="radial-layout">
        {/* 中心装饰圆环 */}
        <div className="center-decor">
          <svg className="center-ring" viewBox="0 0 200 200">
            <defs>
              <linearGradient id="dayGlow" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" style={{ stopColor: '#f59e0b', stopOpacity: 0.8 }} />
                <stop offset="50%" style={{ stopColor: '#fcd34d', stopOpacity: 1 }} />
                <stop offset="100%" style={{ stopColor: '#f59e0b', stopOpacity: 0.8 }} />
              </linearGradient>
              <linearGradient id="nightGlow" x1="0%" y1="100%" x2="100%" y2="0%">
                <stop offset="0%" style={{ stopColor: '#38bdf8', stopOpacity: 0.7 }} />
                <stop offset="50%" style={{ stopColor: '#c084fc', stopOpacity: 1 }} />
                <stop offset="100%" style={{ stopColor: '#38bdf8', stopOpacity: 0.7 }} />
              </linearGradient>
              <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
                <feGaussianBlur stdDeviation="3" result="blur" />
                <feComposite in="SourceGraphic" in2="blur" operator="over" />
              </filter>
            </defs>
            
            <circle 
              cx="100" cy="100" r="95" 
              fill="none" 
              stroke={isNight ? 'rgba(56, 189, 248, 0.1)' : 'rgba(251, 191, 36, 0.1)'} 
              strokeWidth="1"
              className="outermost-ring"
            />

            <circle 
              cx="100" cy="100" r="85" 
              fill="none" 
              stroke={isNight ? 'url(#nightGlow)' : 'url(#dayGlow)'} 
              strokeWidth="1.5"
              strokeDasharray="4,8"
              className="outer-ring"
              filter="url(#glow)"
            />
            
            <circle 
              cx="100" cy="100" r="65" 
              fill="none" 
              stroke={isNight ? 'rgba(192, 132, 252, 0.2)' : 'rgba(252, 211, 77, 0.2)'} 
              strokeWidth="8"
              className="middle-ring"
            />

            <circle 
              cx="100" cy="100" r="45" 
              fill="none" 
              stroke={isNight ? 'url(#nightGlow)' : 'url(#dayGlow)'} 
              strokeWidth="2"
              strokeDasharray="30,10"
              className="inner-ring"
              filter="url(#glow)"
            />
            
            <path 
              d="M100 0 L100 15 M100 185 L100 200 M0 100 L15 100 M185 100 L200 100"
              stroke={isNight ? 'rgba(56, 189, 248, 0.4)' : 'rgba(251, 191, 36, 0.4)'}
              strokeWidth="1.5"
            />

            <g className="decor-dots">
              {Array.from({ length: 12 }).map((_, i) => (
                <circle 
                  key={i}
                  cx={100 + 75 * Math.cos((i) * 30 * Math.PI / 180 - Math.PI / 2)}
                  cy={100 + 75 * Math.sin((i) * 30 * Math.PI / 180 - Math.PI / 2)}
                  r="2.5"
                  fill={isNight ? '#38bdf8' : '#fbbf24'}
                  filter="url(#glow)"
                />
              ))}
            </g>
          </svg>
          
          <div className={cn("center-icon", isNight ? "night" : "")}>
            {isNight ? (
              <Moon className="w-12 h-12 text-blue-400" fill="currentColor" strokeWidth={1} />
            ) : (
              <Sun className="w-12 h-12 text-amber-400" fill="currentColor" strokeWidth={2} />
            )}
          </div>
        </div>

        {/* 玩家座位 */}
        {players.map(player => (
          <PlayerSeat
            key={player.id}
            player={player}
            isCurrentSpeaker={currentSpeakerId === player.id}
            isSelected={selectedTargetId === player.id}
            isHovered={hoveredPlayerId === player.id}
            isMe={myPlayer?.id === player.id}
            showRole={shouldShowRole(player)}
            canSelect={canSelectPlayer(player)}
            selectionMode={selectionMode}
            className="player-seat"
            style={getPlayerPositionStyle(player.id)}
            onClick={(p) => onSelectPlayer?.(p.id)}
            onMouseEnter={(id) => {
              setHoveredPlayerId(id)
              onHoverPlayer?.(id)
            }}
            onMouseLeave={() => {
              setHoveredPlayerId(null)
              onHoverPlayer?.(null)
            }}
            onContextMenu={(p, e) => onRightClickPlayer?.(p.id, e)}
          />
        ))}

        {/* 中央区域插槽 */}
        <div className="center-slot">
          {children}
        </div>
      </div>

      {/* 选择模式提示 */}
      {selectionMode !== 'none' && (
        <div className="selection-hint">
          <div className={cn("hint-content backdrop-blur-xl bg-slate-900/70 shadow-[0_4px_30px_rgba(0,0,0,0.5)] border border-white/10 animate-fade-in-up", selectionModeStyle.glowClass)}>
            <span className="hint-icon text-xl">{selectionModeStyle.icon}</span>
            <span className={cn("hint-text text-sm tracking-wide", selectionModeStyle.textClass)}>
              {selectionModeStyle.text}
            </span>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/game/GameTable.vue
<template>
  <div
    ref="tableRef"
    class="game-table"
    :class="{ 'night-mode': isNight, 'day-mode': !isNight }"
  >
    <!-- 放射状布局容器 -->
    <div class="radial-layout">
      <!-- 中心装饰圆环 -->
      <div class="center-decor">
        <svg class="center-ring" viewBox="0 0 200 200">
          <defs>
            <!-- 日光渐变 -->
            <linearGradient id="dayGlow" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#d4af37;stop-opacity:0.6"/>
              <stop offset="50%" style="stop-color:#f4d03f;stop-opacity:0.8"/>
              <stop offset="100%" style="stop-color:#d4af37;stop-opacity:0.6"/>
            </linearGradient>
            <!-- 月光渐变 -->
            <linearGradient id="nightGlow" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#3b82f6;stop-opacity:0.4"/>
              <stop offset="50%" style="stop-color:#60a5fa;stop-opacity:0.6"/>
              <stop offset="100%" style="stop-color:#3b82f6;stop-opacity:0.4"/>
            </linearGradient>
          </defs>
          
          <!-- 外圈装饰 -->
          <circle 
            cx="100" cy="100" r="90" 
            fill="none" 
            :stroke="isNight ? 'url(#nightGlow)' : 'url(#dayGlow)'" 
            stroke-width="1"
            stroke-dasharray="10,5"
            class="outer-ring"
          />
          
          <!-- 内圈 -->
          <circle 
            cx="100" cy="100" r="45" 
            fill="none" 
            :stroke="isNight ? 'rgba(96, 165, 250, 0.3)' : 'rgba(251, 191, 36, 0.3)'" 
            stroke-width="2"
            class="inner-ring"
          />
          
          <!-- 装饰点 -->
          <g class="decor-dots">
            <circle 
              v-for="i in 12" 
              :key="i"
              :cx="100 + 75 * Math.cos((i - 1) * 30 * Math.PI / 180 - Math.PI / 2)"
              :cy="100 + 75 * Math.sin((i - 1) * 30 * Math.PI / 180 - Math.PI / 2)"
              r="3"
              :fill="isNight ? 'rgba(96, 165, 250, 0.6)' : 'rgba(251, 191, 36, 0.6)'"
            />
          </g>
        </svg>
        
        <!-- 中心图标 -->
        <div class="center-icon" :class="{ night: isNight }">
          {{ isNight ? '🌙' : '☀️' }}
        </div>
      </div>

      <!-- 玩家座位 -->
      <PlayerSeat
        v-for="player in players"
        :key="player.id"
        :player="player"
        :is-current-speaker="currentSpeakerId === player.id"
        :is-selected="selectedTargetId === player.id"
        :is-hovered="hoveredPlayerId === player.id"
        :is-me="myPlayerId === player.id"
        :show-role="shouldShowRole(player)"
        :can-select="canSelectPlayer(player)"
        :selection-mode="selectionMode"
        :style="getPlayerPositionStyle(player.id)"
        class="player-seat"
        @click="handlePlayerClick(player)"
        @mouseenter="handlePlayerHover(player.id)"
        @mouseleave="handlePlayerHover(null)"
        @contextmenu.prevent="handlePlayerRightClick(player, $event)"
      />

      <!-- 中央区域插槽 -->
      <div class="center-slot">
        <slot name="center"></slot>
      </div>
    </div>

    <!-- 选择模式提示 -->
    <Transition name="mode-hint">
      <div v-if="selectionMode !== 'none'" class="selection-hint">
        <div class="hint-content" :class="selectionModeStyle.borderClass">
          <span class="hint-icon">{{ selectionModeStyle.icon }}</span>
          <span class="hint-text" :class="selectionModeStyle.textClass">
            {{ selectionModeStyle.text }}
          </span>
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useGameStore } from '../../stores/gameStore'
import PlayerSeat from './PlayerSeat.vue'
import type { Player, GamePhase } from '../../types'
import { isWolfRole } from '../../types'

interface Props {
  selectionMode?: SelectionMode
  selectedTargetId?: number | null
  currentSpeakerId?: number | null
}

type SelectionMode = 'none' | 'vote' | 'kill' | 'check' | 'protect' | 'poison' | 'save' | 'shoot'

const props = withDefaults(defineProps<Props>(), {
  selectionMode: 'none',
  selectedTargetId: null,
  currentSpeakerId: null
})

const emit = defineEmits<{
  (e: 'select-player', playerId: number): void
  (e: 'hover-player', playerId: number | null): void
  (e: 'right-click-player', playerId: number, event: MouseEvent): void
}>()

const gameStore = useGameStore()
const hoveredPlayerId = ref<number | null>(null)
const tableRef = ref<HTMLElement | null>(null)

const PLAYER_COUNT = 12
const ANGLE_PER_PLAYER = 360 / PLAYER_COUNT

const players = computed(() => gameStore.players)
const myPlayerId = computed(() => gameStore.myPlayer?.id)

const isNight = computed(() => {
  const nightPhases: GamePhase[] = [
    'NIGHT_START', 'NIGHT_WOLF_DISCUSS', 'NIGHT_WOLF_VOTE',
    'NIGHT_SEER', 'NIGHT_WITCH', 'NIGHT_GUARD', 'NIGHT_RESOLVE'
  ]
  return nightPhases.includes(gameStore.currentPhase as GamePhase)
})

const selectionModeStyle = computed(() => {
  const styles: Record<SelectionMode, { icon: string; text: string; borderClass: string; textClass: string }> = {
    none: { icon: '', text: '', borderClass: '', textClass: '' },
    vote: { icon: '🗳️', text: '选择要投票的玩家', borderClass: 'border-blue', textClass: 'text-blue' },
    kill: { icon: '🐺', text: '选择今晚要击杀的目标', borderClass: 'border-red', textClass: 'text-red' },
    check: { icon: '🔮', text: '选择要查验的玩家', borderClass: 'border-purple', textClass: 'text-purple' },
    protect: { icon: '🛡️', text: '选择要守护的玩家', borderClass: 'border-cyan', textClass: 'text-cyan' },
    poison: { icon: '☠️', text: '选择要毒杀的玩家', borderClass: 'border-red', textClass: 'text-red' },
    save: { icon: '💚', text: '选择要救的玩家', borderClass: 'border-green', textClass: 'text-green' },
    shoot: { icon: '🔫', text: '选择要开枪带走的玩家', borderClass: 'border-orange', textClass: 'text-orange' }
  }
  return styles[props.selectionMode] || styles['none']
})

function getPlayerPositionStyle(playerId: number) {
  const angleDegrees = (playerId - 1) * ANGLE_PER_PLAYER - 90
  const angleRadians = angleDegrees * (Math.PI / 180)
  const radius = 42
  const x = 50 + radius * Math.cos(angleRadians)
  const y = 50 + radius * Math.sin(angleRadians)
  return { left: `${x}%`, top: `${y}%` }
}

function shouldShowRole(player: Player): boolean {
  if (player.is_human) return true
  if (!player.is_alive) return true
  const myPlayer = gameStore.myPlayer
  if (myPlayer && isWolfRole(myPlayer.role) && isWolfRole(player.role)) return true
  return false
}

function canSelectPlayer(player: Player): boolean {
  if (props.selectionMode === 'none') return false
  if (!player.is_alive) return false
  const myPlayer = gameStore.myPlayer
  if (!myPlayer) return false

  switch (props.selectionMode) {
    case 'vote': return player.id !== myPlayer.id
    case 'kill': return !isWolfRole(player.role)
    case 'check': return player.id !== myPlayer.id
    case 'protect': return true
    case 'poison': return player.id !== myPlayer.id
    case 'save': return true
    case 'shoot': return player.id !== myPlayer.id
    default: return false
  }
}

function handlePlayerClick(player: Player) {
  if (canSelectPlayer(player)) {
    emit('select-player', player.id)
  }
}

function handlePlayerHover(playerId: number | null) {
  hoveredPlayerId.value = playerId
  emit('hover-player', playerId)
}

function handlePlayerRightClick(player: Player, event: MouseEvent) {
  emit('right-click-player', player.id, event)
}
</script>

<style scoped>
/* ========== 游戏桌面 ========== */
.game-table {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400px;
}

/* ========== 放射状布局 ========== */
.radial-layout {
  position: relative;
  width: min(70vmin, 100%);
  height: min(70vmin, 100%);
  max-width: 520px;
  max-height: 520px;
  aspect-ratio: 1;
}

/* ========== 中心装饰 ========== */
.center-decor {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}

.center-ring {
  width: 100%;
  height: 100%;
}

.outer-ring {
  animation: rotateRing 60s linear infinite;
  transform-origin: center;
}

@keyframes rotateRing {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.inner-ring {
  animation: pulseRing 3s ease-in-out infinite;
}

@keyframes pulseRing {
  0%, 100% { opacity: 0.3; }
  50% { opacity: 0.6; }
}

.decor-dots circle {
  animation: twinkleDot 2s ease-in-out infinite;
}

.decor-dots circle:nth-child(odd) {
  animation-delay: 0.5s;
}

@keyframes twinkleDot {
  0%, 100% { opacity: 0.4; }
  50% { opacity: 1; }
}

.center-icon {
  position: absolute;
  font-size: 3rem;
  animation: floatIcon 3s ease-in-out infinite;
  filter: drop-shadow(0 0 20px rgba(251, 191, 36, 0.5));
}

.center-icon.night {
  filter: drop-shadow(0 0 20px rgba(96, 165, 250, 0.5));
}

@keyframes floatIcon {
  0%, 100% { transform: translateY(0) scale(1); }
  50% { transform: translateY(-5px) scale(1.05); }
}

/* ========== 玩家座位 ========== */
.player-seat {
  position: absolute;
  z-index: 30;
  transform: translate(-50%, -50%);
}

/* ========== 中央插槽 ========== */
.center-slot {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
  z-index: 20;
}

/* ========== 选择模式提示 ========== */
.selection-hint {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 40;
}

.hint-content {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 20px;
  background: rgba(0, 0, 0, 0.85);
  backdrop-filter: blur(10px);
  border-radius: 30px;
  border: 2px solid;
}

.hint-icon {
  font-size: 1.25rem;
}

.hint-text {
  font-size: 0.9rem;
  font-weight: 500;
}

/* 颜色变体 */
.border-blue { border-color: rgba(59, 130, 246, 0.6); }
.border-red { border-color: rgba(239, 68, 68, 0.6); }
.border-purple { border-color: rgba(168, 85, 247, 0.6); }
.border-cyan { border-color: rgba(6, 182, 212, 0.6); }
.border-green { border-color: rgba(34, 197, 94, 0.6); }
.border-orange { border-color: rgba(249, 115, 22, 0.6); }

.text-blue { color: #60a5fa; }
.text-red { color: #f87171; }
.text-purple { color: #c084fc; }
.text-cyan { color: #22d3ee; }
.text-green { color: #4ade80; }
.text-orange { color: #fb923c; }

/* ========== 提示动画 ========== */
.mode-hint-enter-active {
  animation: hintSlideIn 0.3s ease-out;
}

.mode-hint-leave-active {
  animation: hintSlideOut 0.2s ease-in;
}

@keyframes hintSlideIn {
  from {
    opacity: 0;
    transform: translateX(-50%) translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateX(-50%) translateY(0);
  }
}

@keyframes hintSlideOut {
  from {
    opacity: 1;
    transform: translateX(-50%) translateY(0);
  }
  to {
    opacity: 0;
    transform: translateX(-50%) translateY(20px);
  }
}

/* ========== 日夜模式 ========== */
.night-mode, .day-mode {
  background: transparent;
}
</style>
