// frontend/src/pages/GameRoom.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getStoredSessionId, useGameStore } from '../store/useGameStore'
import { cn } from '../lib/utils'
import { GameTable } from '../components/game/GameTable'
import { ActionPanel } from '../components/game/ActionPanel'
import { JudgeArea } from '../components/game/JudgeArea'
import { DialogBox } from '../components/common/DialogBox'
import { SidePanel } from '../components/game/SidePanel'
import { WolfDiscussionModal } from '../components/game/WolfDiscussionModal'
import { VoteModal } from '../components/game/VoteModal'
import { NightActionAnimation } from '../components/game/NightActionAnimation'
import { DiscussionDialog } from '../components/game/DiscussionDialog'
import type { GameLog, VoteRecord, WolfDiscussMessage } from '../types'

export function GameRoom() {
  const navigate = useNavigate()
  const recoveryAttemptedRef = useRef(false)
  const cancelLoading = useGameStore(state => state.cancelLoading)
  const clearSession = useGameStore(state => state.clearSession)
  const currentPhase = useGameStore(state => state.currentPhase)
  const gameLogs = useGameStore(state => state.gameLogs)
  const gameState = useGameStore(state => state.gameState)
  const isCandidate = useGameStore(state => state.isCandidate)
  const isLoading = useGameStore(state => state.isLoading)
  const loadingStartTime = useGameStore(state => state.loadingStartTime)
  const loadingText = useGameStore(state => state.loadingText)
  const myPlayer = useGameStore(state => state.myPlayer)
  const recoverSession = useGameStore(state => state.recoverSession)
  const sessionId = useGameStore(state => state.sessionId)
  const sheriffId = useGameStore(state => state.sheriffId)
  const stopPolling = useGameStore(state => state.stopPolling)
  const winner = useGameStore(state => state.winner)
  const wolfDiscussMessages = useGameStore(state => state.wolfDiscussMessages)
  
  const [loadingElapsed, setLoadingElapsed] = useState(0)
  
  const [showWolfModal, setShowWolfModal] = useState(false)
  const [showVoteModal, setShowVoteModal] = useState(false)
  const [voteType, setVoteType] = useState<'exile' | 'sheriff'>('exile')

  useEffect(() => {
    let timer: ReturnType<typeof setInterval> | undefined
    if (isLoading) {
      setLoadingElapsed(0)
      timer = setInterval(() => {
        if (loadingStartTime > 0) {
          setLoadingElapsed(Math.floor((Date.now() - loadingStartTime) / 1000))
        }
      }, 1000)
    } else {
      setLoadingElapsed(0)
    }
    return () => {
      if (timer) clearInterval(timer)
    }
  }, [isLoading, loadingStartTime])

  const isInNightActionPhase = useMemo(() => {
    const nightActionPhases = [
      'NIGHT_WOLF_DISCUSS',
      'NIGHT_WOLF_VOTE', 
      'NIGHT_SEER',
      'NIGHT_WITCH',
      'NIGHT_GUARD'
    ]
    return nightActionPhases.includes(currentPhase)
  }, [currentPhase])

  const isCurrentActionRole = useMemo(() => {
    const phase = currentPhase
    const role = myPlayer?.role || ''
    
    if (phase === 'NIGHT_WOLF_DISCUSS' || phase === 'NIGHT_WOLF_VOTE') {
      return ['wolf', 'wolf_king'].includes(role)
    }
    if (phase === 'NIGHT_SEER') return role === 'seer'
    if (phase === 'NIGHT_WITCH') return role === 'witch'
    if (phase === 'NIGHT_GUARD') return role === 'guard'
    return false
  }, [currentPhase, myPlayer?.role])

  const shouldShowLoading = useMemo(() => {
    if (!isLoading) return false
    if (isInNightActionPhase && !isCurrentActionRole) return false
    return true
  }, [isLoading, isInNightActionPhase, isCurrentActionRole])

  const showDiscussionDialog = useMemo(() => {
    const phase = currentPhase
    const myRole = myPlayer?.role || ''
    const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
    if (phase === 'NIGHT_WOLF_DISCUSS' && isWolfPlayer) return true
    if (phase === 'DAY_DISCUSS') return true
    return false
  }, [currentPhase, myPlayer?.role])

  const discussionMessages = useMemo(() => {
    const phase = currentPhase
    const myRole = myPlayer?.role || ''
    const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
    
    if (phase === 'NIGHT_WOLF_DISCUSS' && isWolfPlayer) {
      return wolfDiscussMessages.map((message: WolfDiscussMessage) => ({
        id: message.id,
        speakerName: `${message.speaker_id}号`,
        content: message.content,
      }))
    }
    
    if (phase === 'DAY_DISCUSS') {
      const dayLogs = gameLogs.filter(
        (log: GameLog) => log.phase === 'DAY_DISCUSS' && 
               log.type === 'speech' && 
               log.content &&
               log.is_public
      )
      
      return dayLogs.map((log: GameLog) => {
        const match = log.content.match(/^(\d+)号:\s*(.+)$/)
        if (match) {
          return {
            id: log.id,
            speakerName: `${match[1]}号`,
            content: match[2],
          }
        }
        return {
          id: log.id,
          speakerName: log.player_id ? `${log.player_id}号` : '未知',
          content: log.content,
        }
      })
    }
    return []
  }, [currentPhase, myPlayer?.role, wolfDiscussMessages, gameLogs])

  const voteRecords = useMemo<VoteRecord[]>(() => {
    const votes = gameState?.votes || {}
    const pkVotes = gameState?.pk_votes || {}

    const currentVotes = currentPhase === 'DAY_PK_VOTE' || currentPhase === 'DAY_PK_RESULT'
      ? pkVotes
      : votes

    return Object.entries(currentVotes).map(([voterId, targetId]) => ({
      voterId: Number(voterId),
      targetId: targetId as number | null,
      weight: Number(voterId) === sheriffId ? 2 : 1
    }))
  }, [currentPhase, gameState?.pk_votes, gameState?.votes, sheriffId])

  const timeRemaining = gameState?.time_remaining || 60

  const winnerText = useMemo(() => {
    if (winner === 'wolf') return '狼人阵营胜利!'
    if (winner === 'good') return '好人阵营胜利!'
    return '游戏结束'
  }, [winner])

  const winnerTextClass = useMemo(() => {
    if (winner === 'wolf') return 'text-red-500'
    if (winner === 'good') return 'text-green-500'
    return 'text-yellow-500'
  }, [winner])

  const isNight = useMemo(() => {
    const nightPhases = [
      'NIGHT_START',
      'NIGHT_WOLF_DISCUSS',
      'NIGHT_WOLF_VOTE',
      'NIGHT_SEER',
      'NIGHT_WITCH',
      'NIGHT_GUARD',
      'NIGHT_RESOLVE'
    ]
    return nightPhases.includes(currentPhase)
  }, [currentPhase])

  // Watch for phase changes to auto-open modals
  useEffect(() => {
    const myRole = myPlayer?.role || ''
    const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
    const phase = currentPhase

    if (isWolfPlayer && ['NIGHT_WOLF_DISCUSS', 'NIGHT_WOLF_VOTE'].includes(phase)) {
       setShowWolfModal(true)
    }
    if (!phase.startsWith('NIGHT_')) {
      setShowWolfModal(false)
    }

    if (phase === 'DAY_VOTE' || phase === 'DAY_PK_VOTE') {
      setVoteType('exile')
      setShowVoteModal(true)
    } else if (phase === 'SHERIFF_VOTE' && !isCandidate) {
      setVoteType('sheriff')
      setShowVoteModal(true)
    } else if (!['DAY_VOTE_RESULT', 'DAY_PK_RESULT'].includes(phase)) {
      setShowVoteModal(false)
    }
  }, [currentPhase, isCandidate, myPlayer?.role])

  const openWolfModal = () => {
    const myRole = myPlayer?.role || ''
    const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
    if (!isWolfPlayer) {
      // Show error some way (need to sync with gameStore if it handles error string)
      return
    }
    setShowWolfModal(true)
  }

  const returnToHome = () => {
    clearSession()
    navigate('/')
  }

  useEffect(() => {
    const storedSessionId = getStoredSessionId()

    if (!sessionId && storedSessionId && !recoveryAttemptedRef.current) {
      recoveryAttemptedRef.current = true
      recoverSession()
      return
    }

    if (!sessionId && !storedSessionId) {
      navigate('/')
    }
  }, [navigate, recoverSession, sessionId])

  useEffect(() => {
    return () => {
      stopPolling()
    }
  }, [stopPolling])

  // Show loading screen while recovering session
  if (!gameState) {
    return (
      <div className="h-screen flex items-center justify-center bg-slate-950 relative overflow-hidden">
        <img src="/images/game-bg.webp" className="absolute inset-0 w-full h-full object-cover opacity-40" alt="" />
        <div className="absolute inset-0 bg-black/50" />
        <div className="relative z-10 flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-2 border-transparent border-t-amber-400 border-l-amber-400/30 rounded-full animate-spin" />
          <span className="text-white/70 text-sm tracking-wide">正在恢复游戏...</span>
        </div>
      </div>
    )
  }

  return (
    <div className="h-screen flex relative overflow-hidden text-slate-100">

      {/* Background Image - switches between night/day */}
      <img
        src="/images/game-bg.webp"
        className={cn(
          "absolute inset-0 w-full h-full object-cover z-0 transition-opacity duration-1000",
          isNight ? "opacity-100" : "opacity-0"
        )}
        alt=""
      />
      <img
        src="/images/game-bg2.webp"
        className={cn(
          "absolute inset-0 w-full h-full object-cover z-0 transition-opacity duration-1000",
          isNight ? "opacity-0" : "opacity-100"
        )}
        alt=""
      />
      {/* Dark overlay for UI readability */}
      <div className={cn(
        "absolute inset-0 z-0 transition-all duration-1000",
        isNight ? "bg-black/45" : "bg-black/30"
      )} />
      {/* Vignette effect */}
      <div className="absolute inset-0 z-0 pointer-events-none bg-[radial-gradient(ellipse_at_center,transparent_0%,rgba(0,0,0,0.2)_50%,rgba(0,0,0,0.6)_100%)]" />

      {/* Main Game Area */}
      <div className="flex-1 flex flex-col relative z-10 min-w-0 overflow-hidden">
        <div className="h-[100px] shrink-0 z-10 w-full max-w-5xl mx-auto mt-4 px-4">
          <JudgeArea />
        </div>

        <div className="flex-1 relative flex items-center justify-center py-4 px-8 overflow-hidden w-full h-full max-w-6xl mx-auto">
          <div className="w-full h-full flex items-center justify-center transform scale-90 sm:scale-100 lg:scale-105 transition-transform duration-500">
            <GameTable />
          </div>
        </div>

        <div className="z-20 w-full shrink-0">
          <ActionPanel />
        </div>
      </div>

      <DialogBox />

      <div className="relative z-10">
        <SidePanel onOpenWolfModal={openWolfModal} />
      </div>

      <WolfDiscussionModal isOpen={showWolfModal} onClose={() => setShowWolfModal(false)} />

      <VoteModal
        isOpen={showVoteModal}
        voteType={voteType}
        voteRecords={voteRecords}
        timeRemaining={timeRemaining}
        onVote={() => setShowVoteModal(false)}
        onClose={() => setShowVoteModal(false)}
      />

      {/* Game End Overlay */}
      {winner && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80">
          <div className="text-center p-8 bg-gray-900 rounded-lg border-2 border-yellow-500">
            <h1 className={cn("text-4xl font-bold mb-4", winnerTextClass)}>
              {winnerText}
            </h1>
            <p className="text-gray-400 mb-6">游戏结束</p>
            <button
              onClick={returnToHome}
              className="px-8 py-3 bg-blue-600 hover:bg-blue-500 rounded-lg font-bold text-white transition-colors"
            >
              返回首页
            </button>
          </div>
        </div>
      )}

      {/* Loading Overlay */}
      {shouldShowLoading && (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/60 transition-opacity duration-400 ease-in-out">
          <div className="flex flex-col items-center justify-center bg-slate-900/70 backdrop-blur-md p-10 rounded-3xl border border-white/10 shadow-[0_25px_50px_-12px_rgba(0,0,0,0.5)]">
            <div className="relative w-[120px] h-[120px]">
              <div className="absolute inset-0 border-2 border-transparent border-t-sky-400 border-l-sky-400/30 rounded-full animate-[spin_2s_linear_infinite]"></div>
              <div className="absolute inset-[12px] border-2 border-transparent border-b-purple-400 border-r-purple-400/30 rounded-full animate-[spin_3s_linear_infinite_reverse]"></div>
              <div className="absolute inset-[24px] border-2 border-transparent border-t-amber-400 border-l-amber-400/30 rounded-full animate-[spin_4s_linear_infinite]"></div>
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-[2rem] animate-[moonPulse_3s_ease-in-out_infinite]">🌙</div>
            </div>
            <div className="mt-6 text-[1.1rem] font-medium tracking-[0.1em] text-slate-50 text-center uppercase animate-[pulse_2s_ease-in-out_infinite]">
              {loadingText}
            </div>
            {loadingElapsed > 3 && (
              <div className="mt-2 text-[0.875rem] text-slate-400 tabular-nums">
                已等待 {loadingElapsed} 秒
              </div>
            )}
            {loadingElapsed > 5 && (
              <button 
                onClick={() => cancelLoading()}
                className="mt-6 px-8 py-2 bg-red-500/10 border border-red-500/40 rounded-full text-red-300 text-[0.875rem] font-medium tracking-wide transition-all hover:bg-red-500/20 hover:border-red-500/80 hover:shadow-[0_0_15px_rgba(239,68,68,0.3)] hover:-translate-y-px active:translate-y-px"
              >
                取消
              </button>
            )}
          </div>
        </div>
      )}

      <NightActionAnimation />

      <DiscussionDialog
        messages={discussionMessages}
        visible={showDiscussionDialog}
      />

    </div>
  )
}

// frontend/src/views/GameRoom.vue
<template>
  <div class="game-room h-screen flex relative overflow-hidden" :class="isNight ? 'night-bg' : 'day-bg'">
    <!-- Main Game Area -->
    <div class="flex-1 flex flex-col relative z-0 min-w-0 overflow-hidden">
      <!-- Judge Area (Top) -->
      <div class="h-[100px] flex-shrink-0 z-10">
        <JudgeArea />
      </div>

      <!-- Game Table (Center) -->
      <div class="flex-1 relative flex items-center justify-center p-4 overflow-hidden w-full h-full">
        <div class="w-full h-full flex items-center justify-center transform scale-90 sm:scale-100 transition-transform duration-300">
          <GameTable />
        </div>
      </div>

      <!-- Action Panel (Bottom) -->
      <div class="h-auto min-h-[100px] bg-gray-800 border-t border-gray-700 p-4 z-20">
        <ActionPanel />
      </div>
    </div>

    <!-- Dialog Box (Global Overlay) -->
    <div class="absolute inset-0 z-30 pointer-events-none">
      <DialogBox />
    </div>

    <!-- Side Panel (Right) -->
    <SidePanel @open-wolf-modal="openWolfModal" />

    <!-- Wolf Discussion Modal -->
    <WolfDiscussionModal
      v-model="showWolfModal"
    />

    <!-- Vote Modal -->
    <VoteModal
      v-model="showVoteModal"
      :vote-type="voteType"
      :vote-records="voteRecords"
      :time-remaining="timeRemaining"
      @voted="onVoted"
      @close="showVoteModal = false"
    />

    <!-- Game End Overlay -->
    <div
      v-if="gameStore.isGameOver"
      class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-80"
    >
      <div class="text-center p-8 bg-gray-900 rounded-lg border-2 border-yellow-500">
        <h1 class="text-4xl font-bold mb-4" :class="winnerTextClass">
          {{ winnerText }}
        </h1>
        <p class="text-gray-400 mb-6">游戏结束</p>
        <button
          @click="returnToHome"
          class="px-8 py-3 bg-blue-600 hover:bg-blue-500 rounded-lg font-bold text-white transition-colors"
        >
          返回首页
        </button>
      </div>
    </div>

    <!-- Loading Overlay (不在夜间非当前角色行动时显示，避免与NightActionAnimation重叠) -->
    <Transition name="loading-fade">
      <div
        v-if="shouldShowLoading"
        class="fixed inset-0 z-40 flex items-center justify-center bg-black bg-opacity-60"
      >
        <div class="loading-spinner-container">
          <div class="loading-spinner">
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-moon">🌙</div>
          </div>
          <div class="loading-text">{{ gameStore.loadingText }}</div>
          <div class="loading-timer" v-if="loadingElapsed > 3">
            已等待 {{ loadingElapsed }} 秒
          </div>
          <button 
            v-if="loadingElapsed > 5"
            @click="gameStore.cancelLoading()"
            class="loading-cancel-btn"
          >
            取消
          </button>
        </div>
      </div>
    </Transition>

    <!-- Night Action Animation -->
    <NightActionAnimation />

    <!-- Discussion Dialog (Bottom Center) -->
    <DiscussionDialog
      :messages="discussionMessages"
      :visible="showDiscussionDialog"
    />

    <!-- Error Toast -->
    <div
      v-if="gameStore.error"
      class="fixed bottom-20 left-1/2 transform -translate-x-1/2 z-50 px-6 py-3 bg-red-600 text-white rounded-lg shadow-lg"
    >
      {{ gameStore.error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useGameStore } from '../stores/gameStore'
import type { VoteRecord } from '../types'
import GameTable from '../components/game/GameTable.vue'
import ActionPanel from '../components/game/ActionPanel.vue'
import JudgeArea from '../components/game/JudgeArea.vue'
import DialogBox from '../components/game/DialogBox.vue'
import SidePanel from '../components/game/SidePanel.vue'
import WolfDiscussionModal from '../components/game/WolfDiscussionModal.vue'
import VoteModal from '../components/game/VoteModal.vue'
import NightActionAnimation from '../components/game/NightActionAnimation.vue'
import DiscussionDialog from '../components/game/DiscussionDialog.vue'

const router = useRouter()
const gameStore = useGameStore()

// 计算加载已持续的时间（秒）
const loadingElapsed = ref(0)
let loadingTimer: ReturnType<typeof setInterval> | null = null

watch(() => gameStore.isLoading, (loading) => {
  if (loading) {
    loadingElapsed.value = 0
    loadingTimer = setInterval(() => {
      if (gameStore.loadingStartTime > 0) {
        loadingElapsed.value = Math.floor((Date.now() - gameStore.loadingStartTime) / 1000)
      }
    }, 1000)
  } else {
    if (loadingTimer) {
      clearInterval(loadingTimer)
      loadingTimer = null
    }
    loadingElapsed.value = 0
  }
}, { immediate: true })

// 判断是否处于夜间行动阶段（此时NightActionAnimation会显示，不需要Loading Overlay）
const isInNightActionPhase = computed(() => {
  const nightActionPhases = [
    'NIGHT_WOLF_DISCUSS',
    'NIGHT_WOLF_VOTE', 
    'NIGHT_SEER',
    'NIGHT_WITCH',
    'NIGHT_GUARD'
  ]
  return nightActionPhases.includes(gameStore.currentPhase)
})

// 判断当前玩家是否是夜间行动的角色
const isCurrentActionRole = computed(() => {
  const phase = gameStore.currentPhase
  const role = gameStore.myPlayer?.role || ''
  
  if (phase === 'NIGHT_WOLF_DISCUSS' || phase === 'NIGHT_WOLF_VOTE') {
    return ['wolf', 'wolf_king'].includes(role)
  }
  if (phase === 'NIGHT_SEER') return role === 'seer'
  if (phase === 'NIGHT_WITCH') return role === 'witch'
  if (phase === 'NIGHT_GUARD') return role === 'guard'
  return false
})

// 是否应该显示Loading Overlay（夜间非当前角色行动时不显示，使用NightActionAnimation代替）
const shouldShowLoading = computed(() => {
  if (!gameStore.isLoading) return false
  // 如果在夜间阶段且不是当前行动角色，不显示Loading Overlay（NightActionAnimation会显示）
  if (isInNightActionPhase.value && !isCurrentActionRole.value) return false
  return true
})

// 讨论对话框相关
const showDiscussionDialog = computed(() => {
  const phase = gameStore.currentPhase
  const myRole = gameStore.myPlayer?.role || ''
  const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
  
  // 狼人讨论阶段：只有狼人才能看到
  if (phase === 'NIGHT_WOLF_DISCUSS' && isWolfPlayer) {
    return true
  }
  
  // 白天讨论阶段：所有玩家都能看到
  if (phase === 'DAY_DISCUSS') {
    return true
  }
  
  return false
})

// 获取讨论消息
const discussionMessages = computed(() => {
  const phase = gameStore.currentPhase
  const myRole = gameStore.myPlayer?.role || ''
  const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
  
  // 狼人讨论阶段：只显示非公开的狼人消息
  if (phase === 'NIGHT_WOLF_DISCUSS' && isWolfPlayer) {
    const wolfLogs = gameStore.gameLogs.filter(
      log => log.phase === 'NIGHT_WOLF_DISCUSS' && 
             log.type === 'speech' && 
             log.content &&
             !log.is_public // 只显示非公开消息（狼人专属）
    )
    
    return wolfLogs.map(log => {
      // 解析消息内容，提取玩家号和内容
      const match = log.content.match(/^(\d+)号\(狼人\):\s*(.+)$/)
      if (match) {
        return {
          id: log.id,
          speakerName: `${match[1]}号`,
          content: match[2],
          timestamp: Date.now()
        }
      }
      // 如果格式不匹配，尝试直接使用
      return {
        id: log.id,
        speakerName: log.player_id ? `${log.player_id}号` : '未知',
        content: log.content,
        timestamp: Date.now()
      }
    })
  }
  
  // 白天讨论阶段：显示所有公开的讨论消息
  if (phase === 'DAY_DISCUSS') {
    const dayLogs = gameStore.gameLogs.filter(
      log => log.phase === 'DAY_DISCUSS' && 
             log.type === 'speech' && 
             log.content &&
             log.is_public // 只显示公开消息
    )
    
    return dayLogs.map(log => {
      // 解析消息内容，提取玩家号和内容（格式：X号: 内容）
      const match = log.content.match(/^(\d+)号:\s*(.+)$/)
      if (match) {
        return {
          id: log.id,
          speakerName: `${match[1]}号`,
          content: match[2],
          timestamp: Date.now()
        }
      }
      // 如果格式不匹配，尝试直接使用
      return {
        id: log.id,
        speakerName: log.player_id ? `${log.player_id}号` : '未知',
        content: log.content,
        timestamp: Date.now()
      }
    })
  }
  
  return []
})

// Modal states
const showWolfModal = ref(false)
const showVoteModal = ref(false)
const voteType = ref<'exile' | 'sheriff'>('exile')

// 投票记录计算属性 - 从gameStore.votes转换为VoteRecord[]
const voteRecords = computed<VoteRecord[]>(() => {
  const votes = gameStore.gameState?.votes || {}
  const sheriffId = gameStore.sheriffId
  const pkVotes = gameStore.gameState?.pk_votes || {}

  // 根据当前阶段选择使用哪个投票数据
  const currentVotes = gameStore.currentPhase === 'DAY_PK_VOTE' || gameStore.currentPhase === 'DAY_PK_RESULT'
    ? pkVotes
    : votes

  return Object.entries(currentVotes).map(([voterId, targetId]) => ({
    voterId: Number(voterId),
    targetId: targetId as number | null,
    weight: Number(voterId) === sheriffId ? 2 : 1
  }))
})

// 剩余时间
const timeRemaining = computed(() => gameStore.gameState?.time_remaining || 60)

// Game end computed
const winnerText = computed(() => {
  if (gameStore.winner === 'wolf') return '狼人阵营胜利!'
  if (gameStore.winner === 'good') return '好人阵营胜利!'
  return '游戏结束'
})

const winnerTextClass = computed(() => {
  if (gameStore.winner === 'wolf') return 'text-red-500'
  if (gameStore.winner === 'good') return 'text-green-500'
  return 'text-yellow-500'
})

// 判断是否为夜晚阶段
const isNight = computed(() => {
  const nightPhases = [
    'NIGHT_START',
    'NIGHT_WOLF_DISCUSS',
    'NIGHT_WOLF_VOTE',
    'NIGHT_SEER',
    'NIGHT_WITCH',
    'NIGHT_GUARD',
    'NIGHT_RESOLVE'
  ]
  return nightPhases.includes(gameStore.currentPhase)
})

// Watch for phase changes to auto-open modals
watch(
  () => gameStore.currentPhase,
  (phase: string, oldPhase: string) => {
    const myRole = gameStore.myPlayer?.role || ''
    const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)

    // Auto open wolf modal when entering wolf phases (only for wolves)
    if (isWolfPlayer && ['NIGHT_WOLF_DISCUSS', 'NIGHT_WOLF_VOTE'].includes(phase)) {
      if (!['NIGHT_WOLF_DISCUSS', 'NIGHT_WOLF_VOTE'].includes(oldPhase)) {
        // Only auto-open when first entering wolf phase
        showWolfModal.value = true
      }
    }
    // Close wolf modal when leaving night phases entirely
    if (!phase.startsWith('NIGHT_')) {
      showWolfModal.value = false
    }

    // Auto open vote modal during vote phases
    if (phase === 'DAY_VOTE' || phase === 'DAY_PK_VOTE') {
      voteType.value = 'exile'
      showVoteModal.value = true
    } else if (phase === 'SHERIFF_VOTE' && !gameStore.isCandidate) {
      voteType.value = 'sheriff'
      showVoteModal.value = true
    } else if (!['DAY_VOTE_RESULT', 'DAY_PK_RESULT'].includes(phase)) {
      // 只在非结果阶段关闭，让用户能看到投票结果
      showVoteModal.value = false
    }
  }
)

function onVoted(targetId: number) {
  console.log('Voted for:', targetId)
}

function openWolfModal() {
  const myRole = gameStore.myPlayer?.role || ''
  const isWolfPlayer = ['wolf', 'wolf_king'].includes(myRole)
  if (!isWolfPlayer) {
    // 非狼人玩家尝试打开狼人讨论，显示错误提示
    gameStore.error = '仅狼人可以使用此功能'
    setTimeout(() => {
      gameStore.error = null
    }, 3000)
    return
  }
  showWolfModal.value = true
}

function returnToHome() {
  gameStore.clearSession()
  router.push('/')
}

onMounted(() => {
  // Try to recover existing session
  gameStore.recoverSession()

  // If no session, redirect to home
  if (!gameStore.sessionId) {
    router.push('/')
  }
})

onUnmounted(() => {
  gameStore.stopPolling()
})
</script>

<style scoped>
.game-room {
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  background-attachment: fixed;
  transition: background-image 0.5s ease-in-out;
}

/* 夜晚背景 */
.night-bg {
  background-image: url('/images/game-bg.jpg');
}

/* 白天背景 */
.day-bg {
  background-image: url('/images/game-bg2.jpg');
}

/* 加载动画 */
.loading-spinner-container {
  display: flex;
  align-items: center;
  justify-content: center;
}

.loading-spinner {
  position: relative;
  width: 120px;
  height: 120px;
}

.spinner-ring {
  position: absolute;
  inset: 0;
  border: 3px solid transparent;
  border-radius: 50%;
  animation: spinnerRotate 1.5s linear infinite;
}

.spinner-ring:nth-child(1) {
  border-top-color: #d4af37;
  animation-duration: 1.5s;
}

.spinner-ring:nth-child(2) {
  inset: 10px;
  border-right-color: #8b5cf6;
  animation-duration: 2s;
  animation-direction: reverse;
}

.spinner-ring:nth-child(3) {
  inset: 20px;
  border-bottom-color: #60a5fa;
  animation-duration: 2.5s;
}

.spinner-moon {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 2.5rem;
  animation: moonPulse 2s ease-in-out infinite;
}

@keyframes spinnerRotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

@keyframes moonPulse {
  0%, 100% { 
    transform: translate(-50%, -50%) scale(1);
    filter: drop-shadow(0 0 10px rgba(96, 165, 250, 0.5));
  }
  50% { 
    transform: translate(-50%, -50%) scale(1.1);
    filter: drop-shadow(0 0 20px rgba(96, 165, 250, 0.8));
  }
}

/* 加载文本 */
.loading-text {
  margin-top: 20px;
  font-size: 1.1rem;
  color: rgba(255, 255, 255, 0.9);
  text-align: center;
  animation: textPulse 2s ease-in-out infinite;
}

.loading-timer {
  margin-top: 8px;
  font-size: 0.85rem;
  color: rgba(255, 255, 255, 0.5);
}

.loading-cancel-btn {
  margin-top: 16px;
  padding: 8px 24px;
  background: rgba(239, 68, 68, 0.2);
  border: 1px solid rgba(239, 68, 68, 0.5);
  border-radius: 8px;
  color: #f87171;
  font-size: 0.9rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.loading-cancel-btn:hover {
  background: rgba(239, 68, 68, 0.3);
  border-color: rgba(239, 68, 68, 0.8);
}

@keyframes textPulse {
  0%, 100% { opacity: 0.8; }
  50% { opacity: 1; }
}

/* 加载动画过渡 */
.loading-fade-enter-active,
.loading-fade-leave-active {
  transition: opacity 0.3s ease;
}

.loading-fade-enter-from,
.loading-fade-leave-to {
  opacity: 0;
}
</style>
